export const Icon = {
	ic_back: require('./ic-back-24.png'),
	ic_absen: require('./icon_absen.png'),
	ic_tugas: require('./icon_tugas.png'),
	ic_nilai: require('./icon_nilai.png'),
	ic_raport: require('./icon_rapor.png'),
	ic_profile: require('./icon_profile.png'),
	ic_notif: require('./icon_notif.png'),
	ic_home: require('./icon_home.png'),
	ic_love: require('./icon_love.png'),
	ic_date: require ('./ic_date.png'),
	ic_stastik: require('./ic_stastik.png'),
	ic_checklist: require('./ic_checklist.png'),
	ic_x: require('./ic_x.png'),
	ic_rectangle: require('./ic_rectangle.png'),
	ic_bca: require('./bca.png'),
	ic_briva: require('./briva.png'),
	ic_alfa: require('./alfa.png'),
	ic_outer: require('./1.png'),
	ic_radio_button: require('./radio-button.png'),
	ic_vector: require('./Vector.png'),
	ic_path: require('./Path.png'),
	ic_search: require('./ic_search.png'),
	ic_filter: require('./ic_filter.png'),
	ic_payment: require('./payment-icon-1.png'),
	ic_riwayat_tugas: require('./payment-icon.png')
}
